# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87ae69cc5a0d9e20f1614dc0d77406da8fbe198dda7ee95a02b55fe1e00488fbc10d411ae22619f44ea3fc2a1cb2e87681a5fc4120a24627090eb9128199f612

test:
  secret_key_base: 69180c72020d3394a5498038bd8c24ec42cedb1a33c195475a4c59890e78ab2a10509da2663367bd20bb87fd24bf1682a22c99dde73e16558d5c3cb4c1989bf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
